import ReduxProvider from "@/Store/ReduxProvider";
import '@radix-ui/themes/styles.css';
import type { Metadata } from "next";
import { Manrope } from 'next/font/google';
import { Tooltip } from "react-tooltip";
import "./globals.css";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body className={manrope.className} >
          {children}
        </body>
      </html>
    </ReduxProvider>
  );
}
