import ReduxProvider from "@/Store/ReduxProvider";
import '@radix-ui/themes/styles.css';
import type { Metadata } from "next";
import { Manrope } from 'next/font/google';
import "./globals.css";
import Header from "@/components/Header";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ReduxProvider>
      <html lang="en">
        <head>
          <link rel="icon" href="/logo-tab.png" />
        </head>
        <body className={manrope.className} suppressHydrationWarning={true} >
          {children}
        </body>
      </html>
    </ReduxProvider>
  );
}
